[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Bryce Wong <brycew.hello@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "requests>=2.32.3",
    "gunicorn>=21.2.0",
]
